### ISSUE TITLE
Literal Operators do not work

### ISSUE THREAD

**Issue by TheOPtimal** [AIIX/krunner-search-skill#12]
When I say: "What is 2 + 2" the script errors out:

```
Traceback (most recent call last):
  File "/home/optimal/mycroft-core/mycroft/skills/mycroft_skill/event_container.py", line 66, in wrapper
    handler(message)
  File "/opt/mycroft/skills/krunner-search-skill.aiix/__init__.py", line 70, in handle_krunner_plasma_calculateskill_intent
    numbers = [int(x) for x in re.split(
  File "/opt/mycroft/skills/krunner-search-skill.aiix/__init__.py", line 70, in <listcomp>
    numbers = [int(x) for x in re.split(
ValueError: invalid literal for int() with base 10: ' 2 + 2'
```
However, when I spell out the word as "P. L. U. S" it works. When using voice, mycroft interprets the word "plus" as a literal plus as in "+". However, this script doesn't recognize this and errors out. I may make a fix for this later if I have the time.

**Comment by TheOPtimal** [comment]
Fixed in #13, closing
